apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: webserver
spec:
  selector:
    app: webserver
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
    name: http
